#!/bin/bash

echo "🔍 TEST: PROPAGATION DES ACTIVE_MODULES - MyFitHero"
echo "================================================="
echo ""
echo "✅ CHANGEMENTS APPLIQUÉS:"
echo "- active_modules ajouté au type User dans App.tsx"
echo "- profile_type ajouté au type User dans App.tsx"
echo "- formatUser() récupère active_modules depuis Supabase"
echo "- convertToUserProfile() propage vers le store Zustand"
echo "- 'other' supprimé du genre pour améliorer l'IA"
echo ""
echo "🧪 FLOW DE TEST À VÉRIFIER:"
echo "1. Inscription → OnboardingQuestionnaire"
echo "2. Sauvegarde: active_modules=['sport', 'nutrition', 'sleep', 'hydration']"
echo "3. Rafraîchissement de page (F5)"
echo "4. Les modules doivent être visibles dans le store"
echo "5. ProtectedRoute ne doit PAS rediriger vers activation"
echo ""
echo "🔧 DEBUG DANS LA CONSOLE:"
echo "- Store: appStore.getState().user.active_modules"
echo "- Auth: auth.user.active_modules"
echo "- Supabase: table user_profiles → active_modules"
echo ""
echo "🎯 RÉSULTAT ATTENDU:"
echo "✅ Modules persistants après rafraîchissement"
echo "✅ Pas de redirection forcée vers activation"
echo "✅ Genre limité à 'male'/'female' pour IA optimale"
echo ""
echo "📱 URL de test: http://localhost:3000"